title: Jason Kim
description: Passionate software engineer with 14 years of experience developing scalable and customer centric APIs and systems through cross-team collaboration and effective communication. Ability to bring positive impact to the business while balancing limited resources.
theme: jekyll-theme-minimal
