title: Jason Kim
description: Passionate software engineer with 16 years of experience developing scalable and customer-centric APIs and systems through cross-team collaboration and effective communication. Ability to bring positive impact to the business while balancing constraints.
theme: jekyll-theme-minimal
