title: Jason Kim
description: Software engineer with 20 years of experience developing scalable and customer focused applications, leveraging product led growth and cross-team collaboration. Ability to bring positive impact to the business while balancing constraints.
theme: jekyll-theme-minimal
